In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s5e10/sample_submission.csv
/kaggle/input/playground-series-s5e10/train.csv
/kaggle/input/playground-series-s5e10/test.csv
/kaggle/input/pss5e10-main/__results__.html
/kaggle/input/pss5e10-main/xgb_5_fold_te_log_transformed.csv
/kaggle/input/pss5e10-main/__notebook__.ipynb
/kaggle/input/pss5e10-main/__output__.json
/kaggle/input/pss5e10-main/Train_org.csv
/kaggle/input/pss5e10-main/test.csv
/kaggle/input/pss5e10-main/final_train.csv
/kaggle/input/pss5e10-main/custom.css
/kaggle/input/pss5e10-main/__results___files/__results___11_2.png

In [2]:
!pip install autogluon.tabular[0]

Collecting autogluon.tabular[0]
  Downloading autogluon.tabular-1.4.0-py3-none-any.whl.metadata (16 kB)
WARNING: autogluon-tabular 1.4.0 does not provide the extra '0'
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[0]) (1.26.4)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[0]) (1.15.3)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[0]) (2.2.3)
Collecting scikit-learn<1.8.0,>=1.4.0 (from autogluon.tabular[0])
  Downloading scikit_learn-1.7.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.tabular[0]) (3.5)
Collecting autogluon.core==1.4.0 (from autogluon.tabular[0])
  Downloading autogluon.core-1.4.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.features==1.4.0 (from autogluon.tabular[0])
  Downloading autogluon.features-1.4.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.4.0->autogluon.tabular[0]) (4.67.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.4.0->autogluon.tabular[0]) (2.32.5)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.4.0->autogluon.tabular[0]) (3.7.2)
Requirement already satisfied: boto3<2,>=1.10 in /usr/local/lib/python3.11/dist-packages (from autogluon.core==1.4.0->autogluon.tabular[0]) (1.40.39)
Collecting autogluon.common==1.4.0 (from autogluon.core==1.4.0->autogluon.tabular[0])
  Downloading autogluon.common-1.4.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pyarrow<21.0.0,>=7.0.0 in /usr/local/lib/python3.11/dist-packages (from autogluon.common==1.4.0->autogluon.core==1.4.0->autogluon.tabular[0]) (19.0.1)
Collecting psutil<7.1.0,>=5.7.3 (from autogluon.common==1.4.0->autogluon.core==1.4.0->autogluon.tabular[0])
  Downloading psutil-7.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.11/dist-packages (from autogluon.common==1.4.0->autogluon.core==1.4.0->autogluon.tabular[0]) (1.5.2)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular[0]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular[0]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular[0]) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<1.8.0,>=1.4.0->autogluon.tabular[0]) (3.6.0)
Requirement already satisfied: botocore<1.41.0,>=1.40.39 in /usr/local/lib/python3.11/dist-packages (from boto3<2,>=1.10->autogluon.core==1.4.0->autogluon.tabular[0]) (1.40.39)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from boto3<2,>=1.10->autogluon.core==1.4.0->autogluon.tabular[0]) (1.0.1)
Requirement already satisfied: s3transfer<0.15.0,>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from boto3<2,>=1.10->autogluon.core==1.4.0->autogluon.tabular[0]) (0.14.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.4.0->autogluon.tabular[0]) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.4.0->autogluon.tabular[0]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.4.0->autogluon.tabular[0]) (4.59.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.4.0->autogluon.tabular[0]) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.4.0->autogluon.tabular[0]) (25.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.4.0->autogluon.tabular[0]) (11.3.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.4.0->autogluon.tabular[0]) (3.0.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=2.0.0->autogluon.tabular[0]) (1.17.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (2024.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->autogluon.core==1.4.0->autogluon.tabular[0]) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->autogluon.core==1.4.0->autogluon.tabular[0]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->autogluon.core==1.4.0->autogluon.tabular[0]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->autogluon.core==1.4.0->autogluon.tabular[0]) (2025.8.3)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy<2.4.0,>=1.25.0->autogluon.tabular[0]) (2024.2.0)
Downloading autogluon.core-1.4.0-py3-none-any.whl (225 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.1/225.1 kB 5.5 MB/s eta 0:00:00
Downloading autogluon.features-1.4.0-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 3.5 MB/s eta 0:00:00
Downloading autogluon.common-1.4.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 3.9 MB/s eta 0:00:00
Downloading scikit_learn-1.7.2-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 76.8 MB/s eta 0:00:00
Downloading autogluon.tabular-1.4.0-py3-none-any.whl (487 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.3/487.3 kB 23.9 MB/s eta 0:00:00
Downloading psutil-7.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (277 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.0/278.0 kB 18.0 MB/s eta 0:00:00
Installing collected packages: psutil, scikit-learn, autogluon.common, autogluon.features, autogluon.core, autogluon.tabular
  Attempting uninstall: psutil
    Found existing installation: psutil 7.1.0
    Uninstalling psutil-7.1.0:
      Successfully uninstalled psutil-7.1.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
category-encoders 2.7.0 requires scikit-learn<1.6.0,>=1.0.0, but you have scikit-learn 1.7.2 which is incompatible.
cesium 0.12.4 requires numpy<3.0,>=2.0, but you have numpy 1.26.4 which is incompatible.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.7.2 which is incompatible.
Successfully installed autogluon.common-1.4.0 autogluon.core-1.4.0 autogluon.features-1.4.0 autogluon.tabular-1.4.0 psutil-7.0.0 scikit-learn-1.7.2

In [3]:
train = pd.read_csv('/kaggle/input/pss5e10-main/final_train.csv')
# train = train.fillna(0)
test = pd.read_csv('/kaggle/input/pss5e10-main/test.csv')
test = test.drop(columns='accident_risk')

In [4]:
TARGET = 'accident_risk'
FEATURES = [col for col in train.columns if col!='accident_risk']

In [5]:
train = train.fillna(0)
test = test.fillna(0)

In [6]:
import shutil, os
old = '/kaggle/working/AutogluonModels'
if os.path.exists(old):
    shutil.rmtree(old)

In [7]:
from autogluon.tabular import TabularPredictor
import warnings
warnings.filterwarnings('ignore')
predictor = TabularPredictor(label=TARGET, eval_metric='rmse', problem_type='regression', path=f'AutogluonModels/run_0')

predictor.fit(
    train_data=train,
    time_limit=18000,
    presets='best_quality',
    num_bag_folds=7,
    num_stack_levels=3,         # Deeper stacking
    num_bag_sets=3,            # More ensembles
    auto_stack=True,
    raise_on_no_models_fitted=False,
    hyperparameters={
        'GBM': {'tree_method': 'gpu_hist', 'device': 'gpu'},  # LightGBM
        'CAT': {'task_type': 'GPU'},  # CatBoost
        'XGB': {'tree_method': 'gpu_hist', 'gpu_id': 0},  # XGBoost
        'NN_TORCH': {},  # Neural networks with GPU
        'RF': {},         # Random Forest
        'XT': {},         # Extra Trees
        'LR': {},          # Linear Regression
        # You can add others, e.g., KNN if desired:
        'KNN': {}
    },
    verbosity=1,
    num_gpus=1
)

Will use sequential fold fitting strategy because import of ray failed. Reason: ray==2.49.2 detected. 2.10.0 <= ray < 2.45.0 is required. You can use pip to install certain version of ray `pip install "ray>=2.10.0,<2.45.0"`
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: Exception caused XGBoost_BAG_L1 to fail during training... Skipping this model.
		[22:17:53] /workspace/src/context.cc:173: Both `device` and `gpu_id` are specified. Use `device` instead.
Stack trace:
  [bt] (0) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x1ba24e) [0x7b1cb8ec624e]
  [bt] (1) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x2bd90a) [0x7b1cb8fc990a]
  [bt] (2) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x4cc9ef) [0x7b1cb91d89ef]
  [bt] (3) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x32) [0x7b1cb8e694d2]
  [bt] (4) /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7b1dc2e75e2e]
  [bt] (5) /lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7b1dc2e72493]
  [bt] (6) /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0xa4d8) [0x7b1dc2e9d4d8]
  [bt] (7) /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0x9c8e) [0x7b1dc2e9cc8e]
  [bt] (8) /usr/bin/python3(_PyObject_MakeTpCall+0x27c) [0x52f85c]


Detailed Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2171, in _train_and_save
    model = self._train_single(**model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2055, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 1068, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 270, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 389, in _fit
    self._fit_folds(
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 868, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 350, in after_all_folds_scheduled
    self._fit_fold_model(job)
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 355, in _fit_fold_model
    fold_model = self._fit(self.model_base, time_start_fold, time_limit_fold, fold_ctx, self.model_base_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 391, in _fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, num_cpus=num_cpus, num_gpus=num_gpus, **kwargs_fold)
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 1068, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/models/xgboost/xgboost_model.py", line 191, in _fit
    self.model.fit(X=X, y=y, eval_set=eval_set, verbose=False, sample_weight=sample_weight)
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py", line 1090, in fit
    self._Booster = train(
                    ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/training.py", line 176, in train
    bst = cb_container.before_training(bst)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/callback.py", line 159, in before_training
    model = c.before_training(model=model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/models/xgboost/callbacks.py", line 105, in before_training
    model = super().before_training(model=model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/callback.py", line 354, in before_training
    self.starting_round = model.num_boosted_rounds()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 2634, in num_boosted_rounds
    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [22:17:53] /workspace/src/context.cc:173: Both `device` and `gpu_id` are specified. Use `device` instead.
Stack trace:
  [bt] (0) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x1ba24e) [0x7b1cb8ec624e]
  [bt] (1) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x2bd90a) [0x7b1cb8fc990a]
  [bt] (2) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x4cc9ef) [0x7b1cb91d89ef]
  [bt] (3) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x32) [0x7b1cb8e694d2]
  [bt] (4) /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7b1dc2e75e2e]
  [bt] (5) /lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7b1dc2e72493]
  [bt] (6) /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0xa4d8) [0x7b1dc2e9d4d8]
  [bt] (7) /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0x9c8e) [0x7b1dc2e9cc8e]
  [bt] (8) /usr/bin/python3(_PyObject_MakeTpCall+0x27c) [0x52f85c]


	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: Exception caused XGBoost_BAG_L3 to fail during training... Skipping this model.
		[23:05:59] /workspace/src/context.cc:173: Both `device` and `gpu_id` are specified. Use `device` instead.
Stack trace:
  [bt] (0) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x1ba24e) [0x7b1cb8ec624e]
  [bt] (1) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x2bd90a) [0x7b1cb8fc990a]
  [bt] (2) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x4cc9ef) [0x7b1cb91d89ef]
  [bt] (3) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x32) [0x7b1cb8e694d2]
  [bt] (4) /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7b1dc2e75e2e]
  [bt] (5) /lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7b1dc2e72493]
  [bt] (6) /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0xa4d8) [0x7b1dc2e9d4d8]
  [bt] (7) /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0x9c8e) [0x7b1dc2e9cc8e]
  [bt] (8) /usr/bin/python3(_PyObject_MakeTpCall+0x27c) [0x52f85c]


Detailed Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2171, in _train_and_save
    model = self._train_single(**model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2055, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 1068, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 270, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 389, in _fit
    self._fit_folds(
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 868, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 350, in after_all_folds_scheduled
    self._fit_fold_model(job)
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 355, in _fit_fold_model
    fold_model = self._fit(self.model_base, time_start_fold, time_limit_fold, fold_ctx, self.model_base_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 391, in _fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, num_cpus=num_cpus, num_gpus=num_gpus, **kwargs_fold)
  File "/usr/local/lib/python3.11/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 1068, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/models/xgboost/xgboost_model.py", line 191, in _fit
    self.model.fit(X=X, y=y, eval_set=eval_set, verbose=False, sample_weight=sample_weight)
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/sklearn.py", line 1090, in fit
    self._Booster = train(
                    ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/training.py", line 176, in train
    bst = cb_container.before_training(bst)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/callback.py", line 159, in before_training
    model = c.before_training(model=model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/autogluon/tabular/models/xgboost/callbacks.py", line 105, in before_training
    model = super().before_training(model=model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/callback.py", line 354, in before_training
    self.starting_round = model.num_boosted_rounds()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 2634, in num_boosted_rounds
    _check_call(_LIB.XGBoosterBoostedRounds(self.handle, ctypes.byref(rounds)))
  File "/usr/local/lib/python3.11/dist-packages/xgboost/core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [23:05:59] /workspace/src/context.cc:173: Both `device` and `gpu_id` are specified. Use `device` instead.
Stack trace:
  [bt] (0) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x1ba24e) [0x7b1cb8ec624e]
  [bt] (1) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x2bd90a) [0x7b1cb8fc990a]
  [bt] (2) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(+0x4cc9ef) [0x7b1cb91d89ef]
  [bt] (3) /usr/local/lib/python3.11/dist-packages/xgboost/lib/libxgboost.so(XGBoosterBoostedRounds+0x32) [0x7b1cb8e694d2]
  [bt] (4) /lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7b1dc2e75e2e]
  [bt] (5) /lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7b1dc2e72493]
  [bt] (6) /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0xa4d8) [0x7b1dc2e9d4d8]
  [bt] (7) /usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so(+0x9c8e) [0x7b1dc2e9cc8e]
  [bt] (8) /usr/bin/python3(_PyObject_MakeTpCall+0x27c) [0x52f85c]


	Warning: Reducing model 'n_estimators' from 300 -> 155 due to low time. Expected time usage reduced from 925.9s -> 480.0s...
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
	Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.

In [8]:
leaderboard = predictor.leaderboard()
leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L5,-0.055721,root_mean_squared_error,372.816844,12447.351751,0.009577,1.558618,5,True,27
1,WeightedEnsemble_L4,-0.055730,root_mean_squared_error,308.879097,8966.304822,0.008556,0.383092,4,True,22
2,LinearModel_BAG_L3,-0.055733,root_mean_squared_error,279.643354,7643.643393,1.725674,45.632042,3,True,20
3,WeightedEnsemble_L3,-0.055739,root_mean_squared_error,260.029963,5349.667846,0.011952,0.403231,3,True,15
4,ExtraTrees_BAG_L2,-0.055748,root_mean_squared_error,231.066786,4052.786009,24.192274,362.688921,2,True,12
5,LightGBM_BAG_L4,-0.055764,root_mean_squared_error,349.686334,11185.928232,5.646307,77.614347,4,True,23
6,LightGBM_BAG_L3,-0.055772,root_mean_squared_error,284.096775,7678.957417,6.179094,80.946066,3,True,16
7,CatBoost_BAG_L3,-0.055838,root_mean_squared_error,278.676356,7679.543829,0.758675,81.532478,3,True,18
8,ExtraTrees_BAG_L3,-0.055880,root_mean_squared_error,302.146615,7949.665783,24.228935,351.654432,3,True,19
9,ExtraTrees_BAG_L4,-0.055883,root_mean_squared_error,368.268209,11468.078572,24.228182,359.764687,4,True,26
10,LightGBM_BAG_L2,-0.055915,root_mean_squared_error,218.886204,3799.367419,12.011692,109.270332,2,True,9
11,LinearModel_BAG_L2,-0.055936,root_mean_squared_error,208.187092,3736.169953,1.312579,46.072865,2,True,13
12,WeightedEnsemble_L2,-0.055939,root_mean_squared_error,64.981548,538.774192,0.008664,0.478197,2,True,8
13,LightGBM_BAG_L1,-0.055940,root_mean_squared_error,48.125592,249.060744,48.125592,249.060744,1,True,2
14,CatBoost_BAG_L2,-0.055972,root_mean_squared_error,207.776223,3787.856287,0.901710,97.759199,2,True,11
15,CatBoost_BAG_L4,-0.055979,root_mean_squared_error,344.426051,11160.161909,0.386024,51.848024,4,True,25
16,RandomForest_BAG_L2,-0.056016,root_mean_squared_error,235.825737,4986.575694,28.951225,1296.478606,2,True,10
17,CatBoost_BAG_L1,-0.056042,root_mean_squared_error,1.294575,138.699395,1.294575,138.699395,1,True,4
18,RandomForest_BAG_L4,-0.056044,root_mean_squared_error,372.807267,12445.793134,28.767240,1337.479249,4,True,24
19,RandomForest_BAG_L3,-0.056093,root_mean_squared_error,307.144867,8920.289688,29.227187,1322.278337,3,True,17
20,ExtraTrees_BAG_L1,-0.056447,root_mean_squared_error,16.847292,289.235252,16.847292,289.235252,1,True,5
21,RandomForest_BAG_L1,-0.056530,root_mean_squared_error,17.532398,367.023598,17.532398,367.023598,1,True,3
22,NeuralNetTorch_BAG_L3,-0.056535,root_mean_squared_error,281.920462,9226.270530,4.002781,1628.259179,3,True,21
23,NeuralNetTorch_BAG_L2,-0.056870,root_mean_squared_error,210.548200,5685.741428,3.673687,1995.644341,2,True,14
24,NeuralNetTorch_BAG_L1,-0.057188,root_mean_squared_error,3.685249,2613.572924,3.685249,2613.572924,1,True,7
25,LinearModel_BAG_L1,-0.057979,root_mean_squared_error,1.386198,32.084121,1.386198,32.084121,1,True,6
26,KNeighbors_BAG_L1,-0.063032,root_mean_squared_error,118.003209,0.421054,118.003209,0.421054,1,True,1

In [9]:
models = leaderboard['model'].to_list()
oofs_dict = {}
for m in models:
    oofs_dict[m] = predictor.predict_oof(model=m)

oofs_df = pd.DataFrame(oofs_dict)

In [10]:
predictor2 = TabularPredictor.load('/kaggle/working/AutogluonModels/run_0')
test_preds = {}
for m in models:
    test_preds[m] = predictor2.predict(test, model=m)

In [11]:
test_preds_df = pd.DataFrame(test_preds)
test_preds_df

,WeightedEnsemble_L5,WeightedEnsemble_L4,LinearModel_BAG_L3,WeightedEnsemble_L3,ExtraTrees_BAG_L2,LightGBM_BAG_L4,LightGBM_BAG_L3,CatBoost_BAG_L3,ExtraTrees_BAG_L3,ExtraTrees_BAG_L4,...,CatBoost_BAG_L1,RandomForest_BAG_L4,RandomForest_BAG_L3,ExtraTrees_BAG_L1,RandomForest_BAG_L1,NeuralNetTorch_BAG_L3,NeuralNetTorch_BAG_L2,NeuralNetTorch_BAG_L1,LinearModel_BAG_L1,KNeighbors_BAG_L1
0,0.289724,0.289814,0.290577,0.291346,0.292115,0.289796,0.293204,0.295002,0.286311,0.288261,...,0.295211,0.286699,0.282947,0.303857,0.302449,0.305633,0.306763,0.304732,0.302729,0.272
1,0.123218,0.123536,0.123639,0.123700,0.122975,0.123327,0.124758,0.123274,0.124396,0.122913,...,0.122818,0.121899,0.122611,0.120544,0.120227,0.132217,0.128524,0.134027,0.117168,0.088
2,0.181192,0.180742,0.180337,0.179982,0.179918,0.182664,0.180994,0.181952,0.182167,0.181786,...,0.187472,0.180238,0.184388,0.176162,0.176671,0.192775,0.197914,0.200865,0.190230,0.190
3,0.311128,0.310096,0.310015,0.311893,0.312314,0.311912,0.312004,0.309680,0.310066,0.312232,...,0.314187,0.312989,0.310823,0.317455,0.317287,0.322465,0.323937,0.322732,0.393189,0.354
4,0.403352,0.405008,0.404989,0.406270,0.406783,0.402853,0.403108,0.400996,0.404774,0.402834,...,0.392639,0.397922,0.405186,0.408725,0.409216,0.387531,0.393841,0.393668,0.366800,0.388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172580,0.103058,0.103296,0.103488,0.102774,0.102145,0.101709,0.102554,0.101430,0.105601,0.104634,...,0.105168,0.100882,0.101573,0.102798,0.103341,0.113837,0.115308,0.120876,0.106855,0.086
172581,0.518919,0.520607,0.520644,0.520629,0.520981,0.518759,0.519498,0.520677,0.516753,0.513033,...,0.518180,0.511594,0.520271,0.507989,0.506931,0.513642,0.507836,0.514133,0.514560,0.470
172582,0.247146,0.247034,0.247058,0.246768,0.246785,0.247949,0.247402,0.248533,0.246610,0.242323,...,0.249810,0.246910,0.246825,0.238420,0.240877,0.255581,0.259682,0.260972,0.240363,0.282
172583,0.126585,0.127103,0.127276,0.127575,0.126733,0.126055,0.127080,0.128797,0.126679,0.125870,...,0.128154,0.123707,0.125538,0.126076,0.126277,0.136505,0.139199,0.142940,0.128108,0.160
172584,0.488598,0.489404,0.488683,0.488827,0.486809,0.488814,0.489145,0.488130,0.489512,0.486296,...,0.487306,0.486631,0.495893,0.482680,0.484083,0.489893,0.481483,0.482418,0.486877,0.518

In [12]:
samp = pd.read_csv('/kaggle/input/playground-series-s5e10/sample_submission.csv')
samp['accident_risk'] = test_preds_df.iloc[:,0]
samp.to_csv('sample_submission.csv', index=False)

In [13]:
leaderboard.to_csv('leaderboard_autogluon_baseline.csv', index=False)
oofs_df.to_csv('oofs_autogluon_baseline.csv', index=False)
test_preds_df.to_csv('test_preds_autogluon_baseline', index=False)